export { default as CTA } from "./CTA";
export { default as FAQ } from "./FAQ";
export { default as Hero } from "./Hero";
export { default as Industries } from "./Industries";
export { default as RecruitmentProcess } from "./RecruitmentProcess";
export { default as Services } from "./Services";
export { default as Statistics } from "./Statistics";
export { default as Testimonials } from "./Testimonials";
export { default as WhyWorkSync } from "./WhyWorkSync";
